---
- name: Setup and deploy Product API
  hosts: target_vm
  become: yes
  tasks:
    - name: Mise à jour des paquets et installation de Docker
      apt:
        name:
          - docker.io
          - mysql-client
        state: present
        update_cache: yes

    - name: Ensure Docker is started and enabled
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install MySQL Server
      apt:
        name: mysql-server
        state: present

    - name: Start MySQL
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Allow MySQL to listen on all interfaces
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '^bind-address'
        line: 'bind-address = 0.0.0.0'
      notify: Restart MySQL

    - name: Flush handlers
      meta: flush_handlers

    - name: Create database product_db
      shell: mysql -u root -proot -e "CREATE DATABASE IF NOT EXISTS product_db;"

    - name: Pull Docker image of Product API
      docker_image:
        name: "amzeekamara/product-api:latest"
        source: pull

    - name: Stop and remove old container if exists
      docker_container:
        name: product-api
        state: absent

    - name: Run Product API Container
      docker_container:
        name: product-api
        image: "amzeekamara/product-api:latest"
        state: started
        restart_policy: always
        network_mode: host
        env:
          SPRING_DATASOURCE_URL: "jdbc:mysql://localhost:3306/product_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true"
          SPRING_DATASOURCE_USERNAME: "root"
          SPRING_DATASOURCE_PASSWORD: "root"

    - name: Verification du déploiement
      uri:
        url: http://localhost:8086/api/products
        method: GET
        status_code: 200
      register: deploy_check
      until: deploy_check.status == 200
      retries: 20
      delay: 10

  handlers:
    - name: Restart MySQL
      service:
        name: mysql
        state: restarted
